runtime: go120
service: eve-item-parser-server-go
instance_class: B1
basic_scaling:
  max_instances: 2
  idle_timeout: 5m
env_variables:
  SERVE_ADDRESS: 0.0.0.0:8080
  DB_URL: db.sqlite
  # Integer
  DB_MAX_READERS: '##DB_MAX_READERS##'
